// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.8.5

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	caseFieldNames          = builder.RawFieldNames(&Case{})
	caseRows                = strings.Join(caseFieldNames, ",")
	caseRowsExpectAutoSet   = strings.Join(stringx.Remove(caseFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	caseRowsWithPlaceHolder = strings.Join(stringx.Remove(caseFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	caseModel interface {
		Insert(ctx context.Context, data *Case) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*Case, error)
		FindOneByKey(ctx context.Context, key string) (*Case, error)
		Update(ctx context.Context, data *Case) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultCaseModel struct {
		conn  sqlx.SqlConn
		table string
	}

	Case struct {
		Id         uint64       `db:"id"`          // 主键ID
		Key        string       `db:"key"`         // 测试用例标识
		ProblemKey string       `db:"problem_key"` // 题目标识
		Input      string       `db:"input"`       // 测试用例输入
		Output     string       `db:"output"`      // 测试用例期望输出
		Score      int64        `db:"score"`       // 该用例分值(总分100)
		CreateTime time.Time    `db:"create_time"` // 创建时间
		UpdateTime time.Time    `db:"update_time"` // 更新时间
		DeleteTime sql.NullTime `db:"delete_time"` // 删除时间
	}
)

func newCaseModel(conn sqlx.SqlConn) *defaultCaseModel {
	return &defaultCaseModel{
		conn:  conn,
		table: "`case`",
	}
}

func (m *defaultCaseModel) Delete(ctx context.Context, id uint64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultCaseModel) FindOne(ctx context.Context, id uint64) (*Case, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", caseRows, m.table)
	var resp Case
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultCaseModel) FindOneByKey(ctx context.Context, key string) (*Case, error) {
	var resp Case
	query := fmt.Sprintf("select %s from %s where `key` = ? limit 1", caseRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, key)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultCaseModel) Insert(ctx context.Context, data *Case) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?)", m.table, caseRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Key, data.ProblemKey, data.Input, data.Output, data.Score, data.DeleteTime)
	return ret, err
}

func (m *defaultCaseModel) Update(ctx context.Context, newData *Case) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, caseRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.Key, newData.ProblemKey, newData.Input, newData.Output, newData.Score, newData.DeleteTime, newData.Id)
	return err
}

func (m *defaultCaseModel) tableName() string {
	return m.table
}
