// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.8.5

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	problemFieldNames          = builder.RawFieldNames(&Problem{})
	problemRows                = strings.Join(problemFieldNames, ",")
	problemRowsExpectAutoSet   = strings.Join(stringx.Remove(problemFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	problemRowsWithPlaceHolder = strings.Join(stringx.Remove(problemFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	problemModel interface {
		Insert(ctx context.Context, data *Problem) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*Problem, error)
		FindOneByKey(ctx context.Context, key string) (*Problem, error)
		Update(ctx context.Context, data *Problem) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultProblemModel struct {
		conn  sqlx.SqlConn
		table string
	}

	Problem struct {
		Id          uint64       `db:"id"`           // 主键ID
		Key         string       `db:"key"`          // 题目标识
		Title       string       `db:"title"`        // 题目标题
		Description string       `db:"description"`  // 题目描述
		InputDesc   string       `db:"input_desc"`   // 输入格式说明
		OutputDesc  string       `db:"output_desc"`  // 输出格式说明
		SampleCases string       `db:"sample_cases"` // 样例输入输出
		Difficulty  string       `db:"difficulty"`   // 题目难度
		TimeLimit   uint64       `db:"time_limit"`   // 程序运行时间限制(单位: 毫秒)
		MemoryLimit uint64       `db:"memory_limit"` // 程序内存限制(单位: MB)
		Tags        string       `db:"tags"`         // 题目标签
		IsPublished int64        `db:"is_published"` // 是否发布: 1-发布, 0-草稿
		CreateTime  time.Time    `db:"create_time"`  // 创建时间
		UpdateTime  time.Time    `db:"update_time"`  // 更新时间
		DeleteTime  sql.NullTime `db:"delete_time"`  // 删除时间
	}
)

func newProblemModel(conn sqlx.SqlConn) *defaultProblemModel {
	return &defaultProblemModel{
		conn:  conn,
		table: "`problem`",
	}
}

func (m *defaultProblemModel) Delete(ctx context.Context, id uint64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultProblemModel) FindOne(ctx context.Context, id uint64) (*Problem, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", problemRows, m.table)
	var resp Problem
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultProblemModel) FindOneByKey(ctx context.Context, key string) (*Problem, error) {
	var resp Problem
	query := fmt.Sprintf("select %s from %s where `key` = ? limit 1", problemRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, key)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultProblemModel) Insert(ctx context.Context, data *Problem) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, problemRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Key, data.Title, data.Description, data.InputDesc, data.OutputDesc, data.SampleCases, data.Difficulty, data.TimeLimit, data.MemoryLimit, data.Tags, data.IsPublished, data.DeleteTime)
	return ret, err
}

func (m *defaultProblemModel) Update(ctx context.Context, newData *Problem) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, problemRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.Key, newData.Title, newData.Description, newData.InputDesc, newData.OutputDesc, newData.SampleCases, newData.Difficulty, newData.TimeLimit, newData.MemoryLimit, newData.Tags, newData.IsPublished, newData.DeleteTime, newData.Id)
	return err
}

func (m *defaultProblemModel) tableName() string {
	return m.table
}
