// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.8.5

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	submissionCaseFieldNames          = builder.RawFieldNames(&SubmissionCase{})
	submissionCaseRows                = strings.Join(submissionCaseFieldNames, ",")
	submissionCaseRowsExpectAutoSet   = strings.Join(stringx.Remove(submissionCaseFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	submissionCaseRowsWithPlaceHolder = strings.Join(stringx.Remove(submissionCaseFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	submissionCaseModel interface {
		Insert(ctx context.Context, data *SubmissionCase) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*SubmissionCase, error)
		FindOneByKey(ctx context.Context, key string) (*SubmissionCase, error)
		FindOneBySubmissionKeyTestCaseKey(ctx context.Context, submissionKey string, testCaseKey string) (*SubmissionCase, error)
		Update(ctx context.Context, data *SubmissionCase) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultSubmissionCaseModel struct {
		conn  sqlx.SqlConn
		table string
	}

	SubmissionCase struct {
		Id            uint64         `db:"id"`             // 主键ID
		Key           string         `db:"key"`            // 用例执行结果标识
		SubmissionKey string         `db:"submission_key"` // 提交记录标识
		TestCaseKey   string         `db:"test_case_key"`  // 测试用例标识
		UserId        uint64         `db:"user_id"`        // 用户ID
		ProblemKey    string         `db:"problem_key"`    // 题目标识
		Passed        int64          `db:"passed"`         // 是否通过: 1-通过, 0-未通过
		ActualOutput  sql.NullString `db:"actual_output"`  // 代码实际输出(NULL=执行失败)
		ErrorMsg      sql.NullString `db:"error_msg"`      // 执行错误信息
		TimeUsed      sql.NullInt64  `db:"time_used"`      // 该用例执行耗时(单位：毫秒)
		MemoryUsed    sql.NullInt64  `db:"memory_used"`    // 该用例执行内存占用(单位: KB)
		CreateTime    time.Time      `db:"create_time"`    // 创建时间
		UpdateTime    time.Time      `db:"update_time"`    // 更新时间
		DeleteTime    sql.NullTime   `db:"delete_time"`    // 删除时间
	}
)

func newSubmissionCaseModel(conn sqlx.SqlConn) *defaultSubmissionCaseModel {
	return &defaultSubmissionCaseModel{
		conn:  conn,
		table: "`submission_case`",
	}
}

func (m *defaultSubmissionCaseModel) Delete(ctx context.Context, id uint64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultSubmissionCaseModel) FindOne(ctx context.Context, id uint64) (*SubmissionCase, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", submissionCaseRows, m.table)
	var resp SubmissionCase
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultSubmissionCaseModel) FindOneByKey(ctx context.Context, key string) (*SubmissionCase, error) {
	var resp SubmissionCase
	query := fmt.Sprintf("select %s from %s where `key` = ? limit 1", submissionCaseRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, key)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultSubmissionCaseModel) FindOneBySubmissionKeyTestCaseKey(ctx context.Context, submissionKey string, testCaseKey string) (*SubmissionCase, error) {
	var resp SubmissionCase
	query := fmt.Sprintf("select %s from %s where `submission_key` = ? and `test_case_key` = ? limit 1", submissionCaseRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, submissionKey, testCaseKey)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultSubmissionCaseModel) Insert(ctx context.Context, data *SubmissionCase) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, submissionCaseRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Key, data.SubmissionKey, data.TestCaseKey, data.UserId, data.ProblemKey, data.Passed, data.ActualOutput, data.ErrorMsg, data.TimeUsed, data.MemoryUsed, data.DeleteTime)
	return ret, err
}

func (m *defaultSubmissionCaseModel) Update(ctx context.Context, newData *SubmissionCase) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, submissionCaseRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.Key, newData.SubmissionKey, newData.TestCaseKey, newData.UserId, newData.ProblemKey, newData.Passed, newData.ActualOutput, newData.ErrorMsg, newData.TimeUsed, newData.MemoryUsed, newData.DeleteTime, newData.Id)
	return err
}

func (m *defaultSubmissionCaseModel) tableName() string {
	return m.table
}
