// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.8.5

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	testCaseFieldNames          = builder.RawFieldNames(&TestCase{})
	testCaseRows                = strings.Join(testCaseFieldNames, ",")
	testCaseRowsExpectAutoSet   = strings.Join(stringx.Remove(testCaseFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	testCaseRowsWithPlaceHolder = strings.Join(stringx.Remove(testCaseFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	testCaseModel interface {
		Insert(ctx context.Context, data *TestCase) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*TestCase, error)
		FindOneByKey(ctx context.Context, key string) (*TestCase, error)
		Update(ctx context.Context, data *TestCase) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultTestCaseModel struct {
		conn  sqlx.SqlConn
		table string
	}

	TestCase struct {
		Id             uint64       `db:"id"`              // 主键ID
		Key            string       `db:"key"`             // 测试用例标识
		ProblemKey     string       `db:"problem_key"`     // 题目标识
		Input          string       `db:"input"`           // 测试用例输入
		ExpectedOutput string       `db:"expected_output"` // 测试用例期望输出
		Score          uint64       `db:"score"`           // 该用例分值(总分100)
		CreateTime     time.Time    `db:"create_time"`     // 创建时间
		UpdateTime     time.Time    `db:"update_time"`     // 更新时间
		DeleteTime     sql.NullTime `db:"delete_time"`     // 删除时间
	}
)

func newTestCaseModel(conn sqlx.SqlConn) *defaultTestCaseModel {
	return &defaultTestCaseModel{
		conn:  conn,
		table: "`test_case`",
	}
}

func (m *defaultTestCaseModel) Delete(ctx context.Context, id uint64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultTestCaseModel) FindOne(ctx context.Context, id uint64) (*TestCase, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", testCaseRows, m.table)
	var resp TestCase
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTestCaseModel) FindOneByKey(ctx context.Context, key string) (*TestCase, error) {
	var resp TestCase
	query := fmt.Sprintf("select %s from %s where `key` = ? limit 1", testCaseRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, key)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTestCaseModel) Insert(ctx context.Context, data *TestCase) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?)", m.table, testCaseRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Key, data.ProblemKey, data.Input, data.ExpectedOutput, data.Score, data.DeleteTime)
	return ret, err
}

func (m *defaultTestCaseModel) Update(ctx context.Context, newData *TestCase) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, testCaseRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.Key, newData.ProblemKey, newData.Input, newData.ExpectedOutput, newData.Score, newData.DeleteTime, newData.Id)
	return err
}

func (m *defaultTestCaseModel) tableName() string {
	return m.table
}
