// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type CaseDetail struct {
	Input  string `json:"input"`
	Output string `json:"output"`
	Score  int    `json:"score"`
}

type CaseDetailList struct {
	CaseKey string `json:"case_key"`
}

type CaseResult struct {
	CaseKey        string `json:"case_key"`
	Passed         int    `json:"passed"`
	Input          string `json:"input"`
	ActualOutput   string `json:"actual_output"`
	ExpectedOutput string `json:"expected_output"`
	ErrorMsg       string `json:"error_msg"`
	TimeUsed       int    `json:"time_used"`
	MemoryUsed     int    `json:"memory_used"`
}

type CreateCaseDetailRequest struct {
	CaseKey    string `json:"case_key"`
	ProblemKey string `json:"problem_key"`
	Input      string `json:"input"`
	Output     string `json:"output"`
	Score      int    `json:score`
}

type CreateProblemDetailRequest struct {
	ProblemKey  string `json:"problem_key"`
	Title       string `json:"title"`
	Description string `json:"description"`
	Inputdesc   string `json:"input_desc"`
	Outputdesc  string `json:"output_desc"`
	SampleCases string `json:"sample_ceses"`
	Difficulty  string `json:"difficulty"`
	TimeLimit   int    `json:"time_limit"`
	MemoryLimit int    `json:"memory_limit"`
	Tags        string `json:"tags"`
	IsPublished int    `json:"is_published"`
}

type CreateSubmissionDetailRequest struct {
	UserId     int    `json:"user_id"`
	ProblemKey string `json:"problem_key"`
	Code       string `json:"code"`
	Language   string `json:"language"`
}

type CreateSubmissionDetailResponse struct {
	GeneralResponse
	Data SubmissionDetail `json:"data"`
}

type CreateUserRequest struct {
	UserName string `json:"user_name"`
	Password string `json:"password"`
}

type CreateUserTokenRequest struct {
	UserName string `json:"user_name"`
	Password string `json:"password"`
}

type CreateUserTokenResponse struct {
	GeneralResponse
	Data TokenDetail `json:"data"`
}

type DeleteCaseDetailRequest struct {
	CaseKey string `path:"case_key"`
}

type DeleteProblemDetailRequest struct {
	ProblemKey string `path:"problem_key"`
}

type GeneralResponse struct {
	StatusCode int `json:"-"`
}

type ProblemDetail struct {
	Title       string `json:"title"`
	Description string `json:"description"`
	Inputdesc   string `json:"input_desc"`
	Outputdesc  string `json:"output_desc"`
	SampleCases string `json:"sample_ceses"`
	Difficulty  string `json:"difficulty"`
	TimeLimit   int    `json:"time_limit"`
	MemoryLimit int    `json:"memory_limit"`
	Tags        string `json:"tags"`
}

type ProblemListDetail struct {
	ProblemKey string `json:"problem_key"`
	Title      string `json:"title"`
	Difficulty string `json:"difficulty"`
	Tags       string `json:"tags"`
}

type RetrieveCaseDetailRequest struct {
	CaseKey string `path:"case_key"`
}

type RetrieveCaseDetailResponse struct {
	GeneralResponse
	Data CaseDetail `json:"data"`
}

type RetrieveCasesRequest struct {
	ProblemKey string `form:"problem_key",optional`
}

type RetrieveCasesResponse struct {
	GeneralResponse
	Data []CaseDetailList `json:"data"`
}

type RetrieveProblemDetailRequest struct {
	ProblemKey string `path:"problem_key"`
}

type RetrieveProblemDetailResponse struct {
	GeneralResponse
	Data ProblemDetail `json:"data"`
}

type RetrieveProblemsRequest struct {
	Title      string `form:"title",optional`
	Difficulty string `form:"difficulty",optional`
	Tags       string `form:"tags",optional`
}

type RetrieveProblemsResponse struct {
	GeneralResponse
	Data []ProblemListDetail `json:"data"`
}

type RetrieveSubmissionDetailRequest struct {
	SubmissionKey string `path:"submission_key"`
}

type RetrieveSubmissionDetailResponse struct {
	GeneralResponse
	Data SubmissionDetail `json:"data"`
}

type RetrieveSubmissionsRequest struct {
	UserId     int    `path:"user_id"`
	ProblemKey string `path:"problem_key"`
}

type RetrieveSubmissionsResponse struct {
	GeneralResponse
	Data []SubmissionsList `json:"data"`
}

type SubmissionDetail struct {
	Status      string       `json:"status"`
	Score       int          `json:"score"`
	TimeUsed    int          `json:"time_used"`
	MemoryUsed  int          `json:"memory_used"`
	CaseResults []CaseResult `json:"case_results"`
}

type SubmissionsList struct {
	SubmissionKey string `json:"submission_key"`
	Status        string `json:"status"`
	Score         int    `json:"score"`
	SubmitTime    int    `json:"submit_time"`
}

type TokenDetail struct {
	Token string `json:"token"`
}

type UpdateCaseDetailRequest struct {
	CaseKey    string `path:"case_key"`
	ProblemKey string `json:"problem_key",optional`
	Input      string `json:"input",optional`
	Output     string `json:"output",optional`
	Score      *int   `json:score,optional`
}

type UpdateProblemDetailRequest struct {
	ProblemKey  string `path:"problem_key"`
	Title       string `json:"title",optional`
	Description string `json:"description",optional`
	Inputdesc   string `json:"input_desc",optional`
	Outputdesc  string `json:"output_desc",optional`
	SampleCases string `json:"sample_ceses",optional`
	Difficulty  string `json:"difficulty",optional`
	TimeLimit   *int   `json:"time_limit",optional`
	MemoryLimit *int   `json:"memory_limit",optional`
	Tags        string `json:"tags",optional`
	IsPublished *int   `json:"is_published",optional`
}
