// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type CreateUserRequest struct {
	UserName string `json:"user_name"`
	Password string `json:"password"`
}

type CreateUserTokenRequest struct {
	UserName string `json:"user_name"`
	Password string `json:"password"`
}

type CreateUserTokenResponse struct {
	StatusCode int         `json:"-"`
	Data       TokenDetail `json:"data"`
}

type GeneralResponse struct {
	StatusCode int `json:"-"`
}

type TokenDetail struct {
	Token string `json:"token"`
}
