// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	v1user "github.com/dszqbsm/online-judge/api/internal/handler/v1/user"
	"github.com/dszqbsm/online-judge/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.LogInterceptor},
			[]rest.Route{
				{
					// 用户注册
					Method:  http.MethodPost,
					Path:    "/v1/users",
					Handler: v1user.CreateUserHandler(serverCtx),
				},
				{
					// 用户登录
					Method:  http.MethodPost,
					Path:    "/v1/users/auth/token",
					Handler: v1user.CreateUserTokenHandler(serverCtx),
				},
			}...,
		),
	)
}
